(cl:defpackage tum_ics_lacquey_gripper_msgs-srv
  (:use )
  (:export
   "GETGRIPPERSTATE"
   "<GETGRIPPERSTATE-REQUEST>"
   "GETGRIPPERSTATE-REQUEST"
   "<GETGRIPPERSTATE-RESPONSE>"
   "GETGRIPPERSTATE-RESPONSE"
   "SETGRIPPERSTATE"
   "<SETGRIPPERSTATE-REQUEST>"
   "SETGRIPPERSTATE-REQUEST"
   "<SETGRIPPERSTATE-RESPONSE>"
   "SETGRIPPERSTATE-RESPONSE"
  ))

