// Generated by gencpp from file tum_ics_lacquey_gripper_msgs/getGripperState.msg
// DO NOT EDIT!


#ifndef TUM_ICS_LACQUEY_GRIPPER_MSGS_MESSAGE_GETGRIPPERSTATE_H
#define TUM_ICS_LACQUEY_GRIPPER_MSGS_MESSAGE_GETGRIPPERSTATE_H

#include <ros/service_traits.h>


#include <tum_ics_lacquey_gripper_msgs/getGripperStateRequest.h>
#include <tum_ics_lacquey_gripper_msgs/getGripperStateResponse.h>


namespace tum_ics_lacquey_gripper_msgs
{

struct getGripperState
{

typedef getGripperStateRequest Request;
typedef getGripperStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct getGripperState
} // namespace tum_ics_lacquey_gripper_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tum_ics_lacquey_gripper_msgs::getGripperState > {
  static const char* value()
  {
    return "ff0be24d823aa1cfde92641488f9e02a";
  }

  static const char* value(const ::tum_ics_lacquey_gripper_msgs::getGripperState&) { return value(); }
};

template<>
struct DataType< ::tum_ics_lacquey_gripper_msgs::getGripperState > {
  static const char* value()
  {
    return "tum_ics_lacquey_gripper_msgs/getGripperState";
  }

  static const char* value(const ::tum_ics_lacquey_gripper_msgs::getGripperState&) { return value(); }
};


// service_traits::MD5Sum< ::tum_ics_lacquey_gripper_msgs::getGripperStateRequest> should match
// service_traits::MD5Sum< ::tum_ics_lacquey_gripper_msgs::getGripperState >
template<>
struct MD5Sum< ::tum_ics_lacquey_gripper_msgs::getGripperStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tum_ics_lacquey_gripper_msgs::getGripperState >::value();
  }
  static const char* value(const ::tum_ics_lacquey_gripper_msgs::getGripperStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tum_ics_lacquey_gripper_msgs::getGripperStateRequest> should match
// service_traits::DataType< ::tum_ics_lacquey_gripper_msgs::getGripperState >
template<>
struct DataType< ::tum_ics_lacquey_gripper_msgs::getGripperStateRequest>
{
  static const char* value()
  {
    return DataType< ::tum_ics_lacquey_gripper_msgs::getGripperState >::value();
  }
  static const char* value(const ::tum_ics_lacquey_gripper_msgs::getGripperStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tum_ics_lacquey_gripper_msgs::getGripperStateResponse> should match
// service_traits::MD5Sum< ::tum_ics_lacquey_gripper_msgs::getGripperState >
template<>
struct MD5Sum< ::tum_ics_lacquey_gripper_msgs::getGripperStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tum_ics_lacquey_gripper_msgs::getGripperState >::value();
  }
  static const char* value(const ::tum_ics_lacquey_gripper_msgs::getGripperStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tum_ics_lacquey_gripper_msgs::getGripperStateResponse> should match
// service_traits::DataType< ::tum_ics_lacquey_gripper_msgs::getGripperState >
template<>
struct DataType< ::tum_ics_lacquey_gripper_msgs::getGripperStateResponse>
{
  static const char* value()
  {
    return DataType< ::tum_ics_lacquey_gripper_msgs::getGripperState >::value();
  }
  static const char* value(const ::tum_ics_lacquey_gripper_msgs::getGripperStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TUM_ICS_LACQUEY_GRIPPER_MSGS_MESSAGE_GETGRIPPERSTATE_H
