// Generated by gencpp from file tum_ics_lacquey_gripper_msgs/getGripperStateRequest.msg
// DO NOT EDIT!


#ifndef TUM_ICS_LACQUEY_GRIPPER_MSGS_MESSAGE_GETGRIPPERSTATEREQUEST_H
#define TUM_ICS_LACQUEY_GRIPPER_MSGS_MESSAGE_GETGRIPPERSTATEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tum_ics_lacquey_gripper_msgs
{
template <class ContainerAllocator>
struct getGripperStateRequest_
{
  typedef getGripperStateRequest_<ContainerAllocator> Type;

  getGripperStateRequest_()
    {
    }
  getGripperStateRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::tum_ics_lacquey_gripper_msgs::getGripperStateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tum_ics_lacquey_gripper_msgs::getGripperStateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct getGripperStateRequest_

typedef ::tum_ics_lacquey_gripper_msgs::getGripperStateRequest_<std::allocator<void> > getGripperStateRequest;

typedef boost::shared_ptr< ::tum_ics_lacquey_gripper_msgs::getGripperStateRequest > getGripperStateRequestPtr;
typedef boost::shared_ptr< ::tum_ics_lacquey_gripper_msgs::getGripperStateRequest const> getGripperStateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tum_ics_lacquey_gripper_msgs::getGripperStateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tum_ics_lacquey_gripper_msgs::getGripperStateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace tum_ics_lacquey_gripper_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tum_ics_lacquey_gripper_msgs::getGripperStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tum_ics_lacquey_gripper_msgs::getGripperStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tum_ics_lacquey_gripper_msgs::getGripperStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tum_ics_lacquey_gripper_msgs::getGripperStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tum_ics_lacquey_gripper_msgs::getGripperStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tum_ics_lacquey_gripper_msgs::getGripperStateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tum_ics_lacquey_gripper_msgs::getGripperStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::tum_ics_lacquey_gripper_msgs::getGripperStateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::tum_ics_lacquey_gripper_msgs::getGripperStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tum_ics_lacquey_gripper_msgs/getGripperStateRequest";
  }

  static const char* value(const ::tum_ics_lacquey_gripper_msgs::getGripperStateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tum_ics_lacquey_gripper_msgs::getGripperStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::tum_ics_lacquey_gripper_msgs::getGripperStateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tum_ics_lacquey_gripper_msgs::getGripperStateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct getGripperStateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tum_ics_lacquey_gripper_msgs::getGripperStateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::tum_ics_lacquey_gripper_msgs::getGripperStateRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // TUM_ICS_LACQUEY_GRIPPER_MSGS_MESSAGE_GETGRIPPERSTATEREQUEST_H
