// Generated by gencpp from file tum_ics_lacquey_gripper_msgs/GripperState.msg
// DO NOT EDIT!


#ifndef TUM_ICS_LACQUEY_GRIPPER_MSGS_MESSAGE_GRIPPERSTATE_H
#define TUM_ICS_LACQUEY_GRIPPER_MSGS_MESSAGE_GRIPPERSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tum_ics_lacquey_gripper_msgs
{
template <class ContainerAllocator>
struct GripperState_
{
  typedef GripperState_<ContainerAllocator> Type;

  GripperState_()
    : state()
    , stateId(0)  {
    }
  GripperState_(const ContainerAllocator& _alloc)
    : state(_alloc)
    , stateId(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _state_type;
  _state_type state;

   typedef int64_t _stateId_type;
  _stateId_type stateId;





  typedef boost::shared_ptr< ::tum_ics_lacquey_gripper_msgs::GripperState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tum_ics_lacquey_gripper_msgs::GripperState_<ContainerAllocator> const> ConstPtr;

}; // struct GripperState_

typedef ::tum_ics_lacquey_gripper_msgs::GripperState_<std::allocator<void> > GripperState;

typedef boost::shared_ptr< ::tum_ics_lacquey_gripper_msgs::GripperState > GripperStatePtr;
typedef boost::shared_ptr< ::tum_ics_lacquey_gripper_msgs::GripperState const> GripperStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tum_ics_lacquey_gripper_msgs::GripperState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tum_ics_lacquey_gripper_msgs::GripperState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tum_ics_lacquey_gripper_msgs::GripperState_<ContainerAllocator1> & lhs, const ::tum_ics_lacquey_gripper_msgs::GripperState_<ContainerAllocator2> & rhs)
{
  return lhs.state == rhs.state &&
    lhs.stateId == rhs.stateId;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tum_ics_lacquey_gripper_msgs::GripperState_<ContainerAllocator1> & lhs, const ::tum_ics_lacquey_gripper_msgs::GripperState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tum_ics_lacquey_gripper_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tum_ics_lacquey_gripper_msgs::GripperState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tum_ics_lacquey_gripper_msgs::GripperState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tum_ics_lacquey_gripper_msgs::GripperState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tum_ics_lacquey_gripper_msgs::GripperState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tum_ics_lacquey_gripper_msgs::GripperState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tum_ics_lacquey_gripper_msgs::GripperState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tum_ics_lacquey_gripper_msgs::GripperState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6806ba1ebf38d757b7a04e49116d3b97";
  }

  static const char* value(const ::tum_ics_lacquey_gripper_msgs::GripperState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6806ba1ebf38d757ULL;
  static const uint64_t static_value2 = 0xb7a04e49116d3b97ULL;
};

template<class ContainerAllocator>
struct DataType< ::tum_ics_lacquey_gripper_msgs::GripperState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tum_ics_lacquey_gripper_msgs/GripperState";
  }

  static const char* value(const ::tum_ics_lacquey_gripper_msgs::GripperState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tum_ics_lacquey_gripper_msgs::GripperState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# gripper state\n"
"string state\n"
"int64 stateId\n"
;
  }

  static const char* value(const ::tum_ics_lacquey_gripper_msgs::GripperState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tum_ics_lacquey_gripper_msgs::GripperState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
      stream.next(m.stateId);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GripperState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tum_ics_lacquey_gripper_msgs::GripperState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tum_ics_lacquey_gripper_msgs::GripperState_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.state);
    s << indent << "stateId: ";
    Printer<int64_t>::stream(s, indent + "  ", v.stateId);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUM_ICS_LACQUEY_GRIPPER_MSGS_MESSAGE_GRIPPERSTATE_H
