// Generated by gencpp from file tum_ics_lacquey_gripper_msgs/setGripperStateRequest.msg
// DO NOT EDIT!


#ifndef TUM_ICS_LACQUEY_GRIPPER_MSGS_MESSAGE_SETGRIPPERSTATEREQUEST_H
#define TUM_ICS_LACQUEY_GRIPPER_MSGS_MESSAGE_SETGRIPPERSTATEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tum_ics_lacquey_gripper_msgs
{
template <class ContainerAllocator>
struct setGripperStateRequest_
{
  typedef setGripperStateRequest_<ContainerAllocator> Type;

  setGripperStateRequest_()
    : newState()  {
    }
  setGripperStateRequest_(const ContainerAllocator& _alloc)
    : newState(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _newState_type;
  _newState_type newState;





  typedef boost::shared_ptr< ::tum_ics_lacquey_gripper_msgs::setGripperStateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tum_ics_lacquey_gripper_msgs::setGripperStateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct setGripperStateRequest_

typedef ::tum_ics_lacquey_gripper_msgs::setGripperStateRequest_<std::allocator<void> > setGripperStateRequest;

typedef boost::shared_ptr< ::tum_ics_lacquey_gripper_msgs::setGripperStateRequest > setGripperStateRequestPtr;
typedef boost::shared_ptr< ::tum_ics_lacquey_gripper_msgs::setGripperStateRequest const> setGripperStateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tum_ics_lacquey_gripper_msgs::setGripperStateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tum_ics_lacquey_gripper_msgs::setGripperStateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tum_ics_lacquey_gripper_msgs::setGripperStateRequest_<ContainerAllocator1> & lhs, const ::tum_ics_lacquey_gripper_msgs::setGripperStateRequest_<ContainerAllocator2> & rhs)
{
  return lhs.newState == rhs.newState;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tum_ics_lacquey_gripper_msgs::setGripperStateRequest_<ContainerAllocator1> & lhs, const ::tum_ics_lacquey_gripper_msgs::setGripperStateRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tum_ics_lacquey_gripper_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tum_ics_lacquey_gripper_msgs::setGripperStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tum_ics_lacquey_gripper_msgs::setGripperStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tum_ics_lacquey_gripper_msgs::setGripperStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tum_ics_lacquey_gripper_msgs::setGripperStateRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tum_ics_lacquey_gripper_msgs::setGripperStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tum_ics_lacquey_gripper_msgs::setGripperStateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tum_ics_lacquey_gripper_msgs::setGripperStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "99fe01dfe585dc3e99fcbbc1365932c3";
  }

  static const char* value(const ::tum_ics_lacquey_gripper_msgs::setGripperStateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x99fe01dfe585dc3eULL;
  static const uint64_t static_value2 = 0x99fcbbc1365932c3ULL;
};

template<class ContainerAllocator>
struct DataType< ::tum_ics_lacquey_gripper_msgs::setGripperStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tum_ics_lacquey_gripper_msgs/setGripperStateRequest";
  }

  static const char* value(const ::tum_ics_lacquey_gripper_msgs::setGripperStateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tum_ics_lacquey_gripper_msgs::setGripperStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# set gripper state\n"
"string newState\n"
;
  }

  static const char* value(const ::tum_ics_lacquey_gripper_msgs::setGripperStateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tum_ics_lacquey_gripper_msgs::setGripperStateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.newState);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct setGripperStateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tum_ics_lacquey_gripper_msgs::setGripperStateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tum_ics_lacquey_gripper_msgs::setGripperStateRequest_<ContainerAllocator>& v)
  {
    s << indent << "newState: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.newState);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUM_ICS_LACQUEY_GRIPPER_MSGS_MESSAGE_SETGRIPPERSTATEREQUEST_H
