// Generated by gencpp from file tum_ics_lacquey_gripper_msgs/setGripperStateResponse.msg
// DO NOT EDIT!


#ifndef TUM_ICS_LACQUEY_GRIPPER_MSGS_MESSAGE_SETGRIPPERSTATERESPONSE_H
#define TUM_ICS_LACQUEY_GRIPPER_MSGS_MESSAGE_SETGRIPPERSTATERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tum_ics_lacquey_gripper_msgs
{
template <class ContainerAllocator>
struct setGripperStateResponse_
{
  typedef setGripperStateResponse_<ContainerAllocator> Type;

  setGripperStateResponse_()
    : ok(false)  {
    }
  setGripperStateResponse_(const ContainerAllocator& _alloc)
    : ok(false)  {
  (void)_alloc;
    }



   typedef uint8_t _ok_type;
  _ok_type ok;





  typedef boost::shared_ptr< ::tum_ics_lacquey_gripper_msgs::setGripperStateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tum_ics_lacquey_gripper_msgs::setGripperStateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct setGripperStateResponse_

typedef ::tum_ics_lacquey_gripper_msgs::setGripperStateResponse_<std::allocator<void> > setGripperStateResponse;

typedef boost::shared_ptr< ::tum_ics_lacquey_gripper_msgs::setGripperStateResponse > setGripperStateResponsePtr;
typedef boost::shared_ptr< ::tum_ics_lacquey_gripper_msgs::setGripperStateResponse const> setGripperStateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tum_ics_lacquey_gripper_msgs::setGripperStateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tum_ics_lacquey_gripper_msgs::setGripperStateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tum_ics_lacquey_gripper_msgs::setGripperStateResponse_<ContainerAllocator1> & lhs, const ::tum_ics_lacquey_gripper_msgs::setGripperStateResponse_<ContainerAllocator2> & rhs)
{
  return lhs.ok == rhs.ok;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tum_ics_lacquey_gripper_msgs::setGripperStateResponse_<ContainerAllocator1> & lhs, const ::tum_ics_lacquey_gripper_msgs::setGripperStateResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tum_ics_lacquey_gripper_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tum_ics_lacquey_gripper_msgs::setGripperStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tum_ics_lacquey_gripper_msgs::setGripperStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tum_ics_lacquey_gripper_msgs::setGripperStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tum_ics_lacquey_gripper_msgs::setGripperStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tum_ics_lacquey_gripper_msgs::setGripperStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tum_ics_lacquey_gripper_msgs::setGripperStateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tum_ics_lacquey_gripper_msgs::setGripperStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6f6da3883749771fac40d6deb24a8c02";
  }

  static const char* value(const ::tum_ics_lacquey_gripper_msgs::setGripperStateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6f6da3883749771fULL;
  static const uint64_t static_value2 = 0xac40d6deb24a8c02ULL;
};

template<class ContainerAllocator>
struct DataType< ::tum_ics_lacquey_gripper_msgs::setGripperStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tum_ics_lacquey_gripper_msgs/setGripperStateResponse";
  }

  static const char* value(const ::tum_ics_lacquey_gripper_msgs::setGripperStateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tum_ics_lacquey_gripper_msgs::setGripperStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool ok\n"
"\n"
;
  }

  static const char* value(const ::tum_ics_lacquey_gripper_msgs::setGripperStateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tum_ics_lacquey_gripper_msgs::setGripperStateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ok);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct setGripperStateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tum_ics_lacquey_gripper_msgs::setGripperStateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tum_ics_lacquey_gripper_msgs::setGripperStateResponse_<ContainerAllocator>& v)
  {
    s << indent << "ok: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ok);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUM_ICS_LACQUEY_GRIPPER_MSGS_MESSAGE_SETGRIPPERSTATERESPONSE_H
